### ISSUE TITLE
Cluster similar to qgis2web (leaflet) - wish

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2o.gis#10]
Hello,
is it possible to get a similar cluster function for qgis2opengis?
I have seen this:
[Dynamic clusters](https://openlayers.org/en/latest/examples/clusters-dynamic.html)

![cluster](https://github.com/user-attachments/assets/02a0d2cb-763d-4517-a47b-4e304a7fb7ce)

That would be great!

Greetings

**Comment by andreaordonselli** [comment]
I should work on it a little but I think it is feasible. I sign it among the things to do.
