### ISSUE TITLE
Smartphone display: "Legend" button

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2o.gis#11]
![legend portrait](https://github.com/user-attachments/assets/31892d17-c5a6-4315-b87f-6c09361bfd63)
Smartphone 1 ("normal size"): Shows "legend" already in portrait orientation

![legend landscape](https://github.com/user-attachments/assets/4f47fb6a-6b72-4857-81c0-ab3b9b9290d4)
Smartphone 2 (a little larger): Shows "legend" when the device is rotated to landscape and then the browser is refreshed. 

Is it possible to hide this button?

Thanks and greetings

QGIS 3.36.3
qgis2opengis 2.21
Browser: Chrome

**Comment by andreaordonselli** [comment]
Thanks for reporting, I have already fixed the bug for the next release

**Comment by andreaordonselli** [comment]
This issue has been resolved in the v2.22.0 release
Thanks for your report
