### ISSUE TITLE
The search address marker is not in the same position when zooming in/out.

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2o.gis#16]
For my example, the search address is:
Via Leopardi, 26, 61038 Orciano di Pesaro
Result:
![search address marker with different positions zoom in out](https://github.com/user-attachments/assets/ba8c2323-fd60-4c54-aa2e-75383229f643)

Note: In your map on https://www.opengis.it/demo/ I can not see the green marker. Another version?

[Related topic](https://gis.stackexchange.com/questions/486555/qgis-points-move-relative-to-the-osm-basemap-when-zoomed-in-or-out-while-using-o)

QGIS 3.36.3
qgis2o.gis 2.22

**Comment by andreaordonselli** [comment]
Thanks for the report. I fixed it. An older version of O.GIS was published online.

The problem on gis.stackexchange.com is not related, in our case the marker was not visible because the link that calls it was wrong.
