### ISSUE TITLE
Link with popup and highlighting

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2o.gis#17]
With the “quick search” function, the result is
- is displayed in the center of the screen
- Popup is opened
- Point/line/polygon is highlighted in color

Question:
Is it possible to generate links to individual content, with popup and color highlighting as with “quick search”?

Background to the question:
A specific map content is to be linked in a text. If the user clicks on this link, they want to find out more about it straight away. An extra click to open the popup is an unnecessary step.
And: If several points are close together, highlighting is required for quick visual recognition.

Greetings

**Comment by andreaordonselli** [comment]
You want permalinks external to the project that when clicked open the map at the correct zoom and queried the feature, right?
The query will highlight the item and open the popup.

**Comment by jukos** [comment]
Yes.

**Comment by andreaordonselli** [comment]
I will bring the update in the next release, in the meantime I ask you to test the functionality and let me know if you have any problems.
It was a good challenge. Thank you.

At the bottom of your index.html add this code before closing the `</body>`

```javascript
<script>

			// permalink to query feature
				
			// Check if the 'find' parameter exists in the permalink
			if (permalink.hasUrlParam('find')) {
				// Extract the value of the 'find' parameter
				var urlFindParam = permalink.getUrlParam('find');
				
				// Break down the string 'find' by commas
				var findParams = urlFindParam.split(',');
				
				// The first element is always the layer (based on "popuplayertitle")
				var layerTitle = findParams[0].trim(); 
				
				// The following elements represent the fields for searching for the feature
				var searchCriteria = {};
				findParams.slice(1).forEach(function(param) {
					var keyValue = param.split(':');
					if (keyValue.length === 2) {
						searchCriteria[keyValue[0].trim()] = keyValue[1].trim();
					}
				});
				
				// Find the layer corresponding to the 'popuplayertitle' property
				var selectedLayer;
				allLayers.forEach(function(layer) {
					if (layer.get('popuplayertitle') === layerTitle) { 
						selectedLayer = layer;
					}
				});
				
				if (selectedLayer) {		
					// Get alias mapping from layer
					var fieldAliases = selectedLayer.get('fieldAliases') || {};
					
					// Convert defined search fields based on aliases
					var convertedSearchCriteria = {};
					for (var alias in searchCriteria) {
						var valueCriteria = searchCriteria[alias];
						// If the alias is present in the aliases, find the corresponding effective field
						var actualField = getKeyByValue(fieldAliases, alias) || alias;
						convertedSearchCriteria[actualField] = valueCriteria;
					}	
					
					// Find the matching feature using the converted search criteria
					var features = selectedLayer.getSource().getFeatures();
					
					var featureFound = features.find(function(f) {				
						var match = true;
						
						for (var field in convertedSearchCriteria) {
							var valueCriteria = convertedSearchCriteria[field];
							var valueFeature = f.get(field);
							
							// If the feature value is a number, compare as a number
							if (!isNaN(valueFeature)) {
								// Remove any units of measurement from the search criterion (e.g. '125.32m' -> '125.32')
								valueCriteria = parseFloat(valueCriteria.replace(/[^0-9.-]/g, ''));
								
								// Compare numerically
								if (parseFloat(valueFeature) !== valueCriteria) {
									match = false;
									break;
								}
							} else {
								// Compare as string
								if (valueFeature !== valueCriteria) {
									match = false;
									break;
								}
							}
						}

						/* if (match) {
							console.log('Find feature:', f);
						} else {
							console.log('No match fot this feature.');
						} */

						return match;
					});

					if (featureFound) {			
						// Simulate selection to activate SearchFeature's 'select' function
						// The selection is configured in the base code with search.on...
						search.dispatchEvent({
							type: 'select',
							search: featureFound
						});
					}/* else {
						console.log('No feature found with this criteria:', searchCriteria);
					}*/
				}/* else {
					console.log('Layer not found with popuplayertitle:', layerTitle);
				}*/
				
				// Remove the "find" parameter from the URL using setUrlParam without specifying the value
				permalink.setUrlParam('find');
			}

			// Funzione per ottenere la chiave in base al valore (invertire gli alias)
			function getKeyByValue(object, value) {
				return Object.keys(object).find(key => object[key] === value);
			}
</scrpit>
```


Now write the permalink to your feature by following these steps:
1) open your webgis as you did for the first time
2) add to the bottom of the link you see in the address bar `&find=layerTitle,field1:value1,field2:value1` etc..

where:
- layerTitle is your layer title visible in legend
- field1 is a field name visibile in popup
- value1 is a field value visibile in popup
etc...

You can add "n" criteria to find your feature
The ideal would be to add an "id" field in qgis with a progressive number so as to search only for this

You can test this link:
ORIGINAL LINK: 
https://www.opengis.it/ente/qgis2o.gis/?lon=12.956319&lat=43.705298&z=13.3&l=ComuniLimitrofi:1|Confini:1|Edifici:1|Stradario:1

LINK WITH FIND WITH 2 CRITERIA: 
https://www.opengis.it/ente/qgis2o.gis/?lon=12.956319&lat=43.705298&z=13.3&l=ComuniLimitrofi:1|Confini:1|Edifici:1|Stradario:1&find=Particelle+Censuario,FOGLIO:15,PARTICELLA:17

ANOTHER LINK WITH FIND WITH 1 CRITERIA: 
https://www.opengis.it/ente/qgis2o.gis/?lon=12.956319&lat=43.705298&z=13.3&l=ComuniLimitrofi:1|Confini:1|Edifici:1|Stradario:1&find=Edifici,QuotaGronda:207.04

**Comment by jukos** [comment]
Hello,
first of all, thank you very much for the implementation.
I have noticed one thing:
The “z” specification is not taken into account by the system.
Example:
If I use this URL:
https://www.opengis.it/ente/qgis2o.gis/index.html?lon=12.956319&lat=43.705298&z=14.2&find=Particelle+Censuario,FOGLIO:15,PARTICELLA:17
I have the value “z=14.2”. When the URL is called up, “z=14.2” becomes 
in Chrome: the value “z=16.3”
in M.Edge : the value “z=17.8”
The value does not have to be identical, but it should be approximately the same.

In Firefox, the normal permalink works, but the new permalink does not work properly: the popup is missing. (It's a hint, I have not forgotten that you are not enthusiastic about this browser.....)


> The ideal would be to add an “id” field in qgis with a progressive number so as to search only for this

I can understand your idea, but there is also a good reason to leave it as it is: 
If the headers are displayed in the popup, it is possible to generate a link even without QGIS. This can be an advantage. 


Best regards

**Comment by andreaordonselli** [comment]
I'll explain well.
As soon as the webgis is started it checks if the new find string is present in the URL and does this:
- reads the string
- breaks it into several parts
- find the layer
- find the feature

After finding the feature I use the basic search code to select it and open the popup (this is what happens when you use the simple search and click on an item). This basic code involves zooming in on the feature and opening the popup in order to have the feature visible in full screen. For this reason the zoom changes.

Setting a default zoom is also a disadvantage because you can't know which device users are using, while the automatic search ensures that the feature is at the center.

As you said, I'm sorry for firefox but it has fallen behind and the computer world runs fast, too fast for it.

**Comment by andreaordonselli** [comment]
The code written in this discussion has been present in stable form since v.2.23.0
Anyone can use the permalink, documentation at opengis.it/docs
