### ISSUE TITLE
CSS customization suggestions for mobile devices (landscape)

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2o.gis#24]
I suggest minimal changes so that 
- sidebar
- sidebar button
- fullscreen button

are displayed a little better in the landscape view for mobile devices:

o.gis_style.css:

actual code:
```
.touch.expand {	 
        top: 50px;
	  }
```

new code:
```
.touch.expand {	 
        top: 49px;
	  }
```

ol3-sidbar.css:

current code
```
@media (min-width: 768px) {
    .sidebar {
      top: 6px;
      bottom: 6px;
      transition: width 500ms; } }
```

new code:

```
@media (min-width: 768px) {
    .sidebar {
      top: 4px;
      bottom: 6px;
      transition: width 500ms; } }
```

Best regards

**Comment by andreaordonselli** [comment]
This issue has been resolved in the v2.24.0 release
Thanks for your report
