### ISSUE TITLE
Performance / Preload

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2o.gis#25]
Hello,

if the map is not included as an iframe in a web page, it loads confused without preloader - it doesn't look good. 
(I know that it is possible to embed the map as an iframe in a web page and equip the web page with a preloader, that works )

I have already achieved a much better result by using
in the index.html page all scripts with 
rel=“preload” as="script”
and all css files with 
rel=“preload” as="style”

Result:
PC Chrome: not perfect, but good
PC firefox: not perfect, but good
M.Edge: no changes

Smartphone Android Opera: Perfect! Without stuttering or anything else
Smartphone Android Chrome: Nearly perfect - for a fraction of a second the sidbar bar appears on the left side, see screenshot:
![sidebar left smartphone](https://github.com/user-attachments/assets/d9d41372-1141-46e0-ad0b-1aa01dccfd00)

Do you have any idea how I could make this even better?
I want the map to load perfectly, outside of a web page.
My current solution is certainly only mediocre, there is certainly a much better solution.

I've been looking at this for a while, but I'm not getting any further.
If you think that this is not an issue for this platform, please let me know.

Best regards

**Comment by andreaordonselli** [comment]
Loading js resources, css, json files, etc... is a complex process that in underperforming pc's, or in case of very heavy data, can take several seconds, during which the user sees elements being created and moving. As you have noticed, the sidebar is an element that acquires a css value only while the map is loading, and if it is in a smartphone it flies to the right closed. 

The only way not to see these elements loading one at a time is to place a preloader in the site where the map is hosted, either this a third party site (with iframe), or this the real site where the project is loaded, **OR** **embed the preloader directly in the index.html of the project**: 
- I show the user a blank sheet while behind the sheet all the data is loaded, and as soon as the data is finished loading I remove the blank sheet and the user sees the ready map 

Loading resources with "rel="preload" as="script" and with rel="preload" as="style"" , as you tried, may improve it but not solve it. Here is the embedded preloader solution:

at the end of the **head** section:
```css
<style>
  #preloader {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: white;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 1000;
  }
  #map { display: none; }
</style>
```

at the end of the **body** section:

```html
<div id="preloader">Loading...</div>
<script>
  window.addEventListener('load', () => {
    document.getElementById('preloader').style.display = 'none';

    const mapContainer = document.getElementById('map');
    mapContainer.style.display = 'block';

    if (typeof map !== 'undefined') {
      map.updateSize();
    }
  });
</script>
```

**Comment by jukos** [comment]
Your solution works. Many thanks and best regards

**Comment by andreaordonselli** [comment]
I'm glad.
Remember that you can edit <style> by including an image representing the loading, here is an example https://codepen.io/codersdesign/pen/zYOgajg
