### ISSUE TITLE
Tooltips also for mobile devices [UNSOLVED - Not useful functionality]

### ISSUE THREAD

**Issue by jukos** [andreaordonselli/qgis2o.gis#30]
Hello,

it would be very helpful if there were also icon-tooltips for mobile devices. 
I have discovered this:
[Custom Tooltips](https://openlayers.org/en/latest/examples/button-title.html) - looks pretty good.

Background:
More and more value is being placed on 
- accessibility and 
- usability

In view of the fact that there are some symbols, an additional tooltip would be helpful for many users. It cannot be assumed that everyone immediately knows what the individual symbols mean.

Can something like this be implemented?

Best regards

**Comment by andreaordonselli** [comment]
In the smartphone the only way is to make the label appear after clicking the button as in the example tooltip, but if the user clicks the button immediately afterwards he understands what it is for, whether it is for measuring, whether it is for searching, whether it is for drawing, whether it is for printing ... I don't know if it makes much sense to set up all the labels

**Comment by jukos** [comment]
Thank you for your feedback.
I will reply in detail tomorrow.
Best regards
